language: android
android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-28.0.3                # Build tools version
    - android-28                        # Target SDK version
    - sys-img-armeabi-v7a-android-18    # Emulator

jdk: oraclejdk8

script:
  - cd android
  - ./gradlew build --console=plain
  - ./gradlew detekt --console=plain

env:
  # IDEA_PLUGIN_PUBLICATION_TOKEN environment variable
  - secure: "DgldL9rjH4T7dYXUcluDEhKapo7y4CWl6RzuN50/9NlNdI98netHH1X38fCg7EMVIakDwhWzRUTWAreh0ktO9IcHrkbI6qWP/5erc4GSoyvbJ3fS5mYwgJEPXYN7hj6FXK9rAsflZ/MBZHZaj/7gNQDneW/18IMDvmzyctsAzh5P0h7ncAiELOn4V8CuWqXO8KNsorcxgI1oF81raeCV/sv04LcT7rTNuJju5hlHaYGTNocJyX8twAbBx5mideUMB55HIcuuLRJL7ioSJRHt3hvdSn0JbTGOJNY9UQiPup9dHdogwgSG2dEHCbqGLS67Fi8tftjqNHoLZmEmNE9THllJYcSH9fYlhd5o1jNu0GH+jbLaDsQGHHbmjK2w59r3fyTqPMlEQ2sB4+bnBRpX0uHRnNgJ2r7NucToejf504Zu5lYlVdqaE4rdgWTPAhSH/7RkiZ/rXeGHjBRylMsmkebEN1323HPLbh6sAfIMrQUqc0saschnikrIsXxIunECzidg/3eOXMiMRLW1Ss0OsqQttZYEJDhqOE45JVk9GRzPMDQSjW6ifVgC3TRatIU8k2Nu4/fdblrDzEgSq4vB9z9M6aHoZE4OrVu51B9ZZGQKEkYh5rfPWnjqa2trc1oXfox/YWJgvvkLUUIQ3BkxJ3Wm8EN14kNpXSxf4LjJAwI="

cache:
  directories:
    - $HOME/.gradle

branches:
  except:
    - gh-pages
    - assets

notifications:
  email: false
